### ISSUE TITLE
IContext doesn't implement unleash context

### ISSUE THREAD

**Issue by mattmurph9** [unleash-hosted/unleash-proxy-client-js#14]
IContext interface right now is an object with string keys and string values. It should implement the Unleash Context defined here: https://www.unleash-hosted.com/docs/the-unleash-context/

**Comment by mattmurph9** [comment]
But since IConfig already includes appName and environment should they be excluded from the IContext?

**Comment by ivarconr** [comment]
Thanks, I agree the context interface could have been more explicitly implementing the unleash-context definition.
